#ifndef LIB_PACKBINARIES_GLOBAL_H
#define LIB_PACKBINARIES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIB_PACKBINARIES_LIBRARY)
#  define LIB_PACKBINARIESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIB_PACKBINARIESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIB_PACKBINARIES_GLOBAL_H
